### ISSUE TITLE
decode input type

### ISSUE THREAD

**Issue by vacekj** [mathiasbynens/windows-1250#1]
Hi, I would like to use this module as a polyfill for windows-1250 decoding in browser. I have a response from a server encoded in windows-1250 as ArrayBuffer, what should I pass into the decode method?

Thank you for your reply.

**Comment by vacekj** [comment]
Solved the issue, I will publish an updated version of this package shortly.

**Comment by vacekj** [comment]
Will not publish, use `iconv-lite` instead

**Comment by mathiasbynens** [comment]
🤔

**Comment by vacekj** [comment]
Would you like me to publish it or..? I think it's better to just use iconv-lite since it works in the browser and is pretty small, which were the reasons I originally chose this package.
