### ISSUE TITLE
No .d.ts included in package

### ISSUE THREAD

**Issue by flevi29** [mathiasbynens/windows-1250#2]
Hi!

Types (windows-1250.d.ts) are missing from the published package for me.

**Comment by mathiasbynens** [comment]
Good catch. We’re including the `src` version but are not yet building the distributed version. Will fix.

**Comment by mathiasbynens** [comment]
https://github.com/mathiasbynens/windows-1252/issues/6

**Comment by mathiasbynens** [comment]
Please try with the latest version.

**Comment by flevi29** [comment]
Types work now. Thanks for the quick fix!
